### ISSUE TITLE
Intel AC7260 not available

### ISSUE THREAD

**Issue by JY-DB** [Sniki/Lenovo-Thinkpad-X240#3]
Can you add Intel AC7260 Kext
Thank you very much

(My english is not good, sorry)

**Comment by Sniki** [comment]
> Can you add Intel AC7260 Kext
> Thank you very much
> 
> (My english is not good, sorry)

Im aware of the kext but it is in my opinion not ready for daily usage. I tested the kext but it isn’t stable yet.

I will add the kext once i believe it is ready for daily usage.

Acidanthera is working on making it to work with native Apple Airport Menu instead of Heliport.

So for now, who wants it can add it manually by him/herself.

Thanks !

**Comment by JY-DB** [comment]
Is there a way to use kext?
I have not been successful in teaching online, but others can
